name = "Fabulously Optimized"
version = "1.12.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3ecb9f8954ef4ec8ab310c9fd676ecb0cdd35dd9f5f622809cafbe1da1748df"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
