name = "Fabulously Optimized"
version = "3.0.0-alpha.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9495d428281fa57ae3dff7b251af1c4df827b714213dc28f1a8a549ed784907"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
