name = "Fabulously Optimized"
version = "2.7.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4800b6c37e6b63ef5057eaea500c5729b5506f8ee90e8eefadf9d199fef1806c"

[versions]
fabric = "0.12.12"
minecraft = "1.17.1"
