name = "Fabulously Optimized"
version = "3.1.0-beta.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ab64e83dca783025a6bd1c1e1f04df51755f5ffd8e82135ed3ecb4c12c80e51"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
